server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/aisearch?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    filters: stat,wall,slf4j
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
mybatis:
  type-aliases-package: com.zjj.aisearch.model
  mapper-locations: classpath:mapper/*.xml
